insert into tags (id, name) values (1, 'современная литература');
insert into tags (id, name) values (2, 'классическая литература');
insert into tags (id, name) values (3, 'зарубежная литература');
insert into tags (id, name) values (4, 'фэнтези');
insert into tags (id, name) values (5, 'английская литература');
insert into tags (id, name) values (6, 'русская литература');
insert into tags (id, name) values (7, 'американская литература');
insert into tags (id, name) values (8, 'фантастика');
insert into tags (id, name) values (9, 'детская литература');
insert into tags (id, name) values (10, 'детектив');
insert into tags (id, name) values (11, 'любовь');
insert into tags (id, name) values (12, 'мистика');
insert into tags (id, name) values (13, 'юмор');
insert into tags (id, name) values (14, 'приключения');
insert into tags (id, name) values (15, 'сказка');
insert into tags (id, name) values (16, 'французская литература');
insert into tags (id, name) values (17, 'художественная литература');
insert into tags (id, name) values (18, 'англия');
insert into tags (id, name) values (19, 'психология');
insert into tags (id, name) values (20, 'философия');
insert into tags (id, name) values (21, 'экранизировано');
insert into tags (id, name) values (22, 'любимое');
insert into tags (id, name) values (23, 'антиутопия');
insert into tags (id, name) values (24, 'books you must read before you die');
insert into tags (id, name) values (25, 'роман');
insert into tags (id, name) values (26, 'франция');
insert into tags (id, name) values (27, 'дайте две');
insert into tags (id, name) values (28, 'young adult');
insert into tags (id, name) values (29, 'война');
insert into tags (id, name) values (30, 'история');
insert into tags (id, name) values (31, 'флэшмоб 2016');
insert into tags (id, name) values (32, 'детство');
insert into tags (id, name) values (33, 'жизнь');
insert into tags (id, name) values (34, 'драма');
insert into tags (id, name) values (35, 'россия');
insert into tags (id, name) values (36, 'книжное путешествие');
insert into tags (id, name) values (37, 'советская литература');
insert into tags (id, name) values (38, 'триллер');
insert into tags (id, name) values (39, 'америка');
insert into tags (id, name) values (40, 'немецкая литература');
insert into tags (id, name) values (41, 'вампиры');
insert into tags (id, name) values (42, 'школьная программа');
insert into tags (id, name) values (43, 'рассказы');
insert into tags (id, name) values (44, 'магия');
insert into tags (id, name) values (45, 'дети');
insert into tags (id, name) values (46, 'русская классика');
insert into tags (id, name) values (47, 'флэшмоб 2015');
insert into tags (id, name) values (48, 'биография');
insert into tags (id, name) values (49, 'english');