package com.example.mybookshopapp.data;

import com.example.mybookshopapp.data.book.Book;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author entity")
public class Author implements Comparable<Author>{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Long id;

    @ManyToMany
    @JoinTable(
            name = "book2author",
            joinColumns = @JoinColumn(name = "author_id"),
            inverseJoinColumns = @JoinColumn(name = "book_id")
    )
    private List<Book> books;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("authors photo")
    private String photo;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("mnemonic identity sequence of characters")
    private String slug;

    @Column(columnDefinition = "VARCHAR(255)", nullable = false)
    @ApiModelProperty("authors name")
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("author description text")
    private String description;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Book> getBooks() {
        return books;
    }

    public void setBooks(List<Book> books) {
        this.books = books;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return name;
    }

    @Override
    public int compareTo(Author o) {
        return name.compareTo(o.name);
    }
}
